# Generated by Django 5.0 on 2026-01-18 14:51

import socio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=socio.models.socio_foto_upload),
        ),
    ]
