# Generated by Django 5.0 on 2026-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_socio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
